import fs from "fs";
import path from "path";
import archiver from "archiver";
import crypto from "crypto";
import { getDb } from "@/lib/db";
import {
  evidenceArtifacts,
  exports as exportsTable,
} from "@/lib/db/schema";
import { eq, desc } from "drizzle-orm";
import { generateControlMatrixCsv } from "./csv";
import { generateManifest } from "./manifest";

interface ExportResult {
  id: string;
  filename: string;
  storagePath: string;
  sizeBytes: number;
}

const EXPORT_README = `# Complyt Evidence Pack

This archive contains compliance evidence artifacts generated by Complyt.

## Contents

| File | Description |
|------|-------------|
| sbom.json | CycloneDX 1.5 Software Bill of Materials |
| osv.json | OSV vulnerability scan results |
| osv_enriched.json | Vulnerabilities enriched with CISA KEV + EPSS |
| sast.json | Static Application Security Testing results |
| secrets.json | Hardcoded secret and credential detection results |
| license-audit.json | License compliance audit results |
| dockerfile-lint.json | Dockerfile security lint results |
| container-scan.json | Container image vulnerability scan results |
| cspm-aws.json | AWS Cloud Security Posture Management audit results |
| dast.json | Dynamic Application Security Testing results |
| control-matrix.csv | Compliance control status matrix |
| evidence-manifest.json | Artifact metadata with SHA-256 hashes |
| README.md | This file |

## Provenance

All artifacts include SHA-256 integrity hashes in the evidence-manifest.json.
Timestamps are in ISO 8601 format (UTC).

## Data Sources

- SBOM: Generated from project dependencies (CycloneDX 1.5 format)
- OSV: Queried from https://api.osv.dev/v1/query
- KEV: Downloaded from https://www.cisa.gov/sites/default/files/feeds/known_exploited_vulnerabilities.json (CC0 license)
- EPSS: Queried from https://api.first.org/data/v1/epss

## License

Evidence data is provided under the terms of the original data sources.
The Complyt tool is licensed under Apache-2.0.
`;

export async function generateExportZip(
  workspaceId: string,
  exportName?: string
): Promise<ExportResult> {
  const db = getDb();
  const exportId = crypto.randomUUID();
  const filename = `audit-pack-${new Date().toISOString().slice(0, 10)}-${exportId.slice(0, 8)}.zip`;
  const exportsDir = path.resolve(process.cwd(), "data", "exports");
  fs.mkdirSync(exportsDir, { recursive: true });
  const zipPath = path.join(exportsDir, filename);

  const latestArtifacts = db
    .select()
    .from(evidenceArtifacts)
    .where(eq(evidenceArtifacts.workspaceId, workspaceId))
    .orderBy(desc(evidenceArtifacts.createdAt))
    .all();

  const artifactsByFilename = new Map<string, typeof latestArtifacts[0]>();
  for (const a of latestArtifacts) {
    if (!artifactsByFilename.has(a.filename)) {
      artifactsByFilename.set(a.filename, a);
    }
  }

  const filesForManifest: Array<{
    filename: string;
    type: string;
    content: string;
  }> = [];

  const archive = archiver("zip", { zlib: { level: 9 } });
  const output = fs.createWriteStream(zipPath);

  const done = new Promise<void>((resolve, reject) => {
    output.on("close", resolve);
    archive.on("error", reject);
  });

  archive.pipe(output);

  for (const [, artifact] of artifactsByFilename) {
    const fullPath = path.resolve(
      process.cwd(),
      "data",
      artifact.storagePath
    );
    if (fs.existsSync(fullPath)) {
      const content = fs.readFileSync(fullPath, "utf-8");
      archive.append(content, { name: artifact.filename });
      filesForManifest.push({
        filename: artifact.filename,
        type: artifact.type,
        content,
      });
    }
  }

  const csv = generateControlMatrixCsv(workspaceId);
  archive.append(csv, { name: "control-matrix.csv" });
  filesForManifest.push({
    filename: "control-matrix.csv",
    type: "control_matrix",
    content: csv,
  });

  const manifest = generateManifest(workspaceId, filesForManifest);
  const manifestJson = JSON.stringify(manifest, null, 2);
  archive.append(manifestJson, { name: "evidence-manifest.json" });

  archive.append(EXPORT_README, { name: "README.md" });

  await archive.finalize();
  await done;

  const stat = fs.statSync(zipPath);
  const storagePath = path.relative(
    path.resolve(process.cwd(), "data"),
    zipPath
  );

  db.insert(exportsTable)
    .values({
      id: exportId,
      workspaceId,
      name: exportName ?? `Audit Pack ${new Date().toISOString().slice(0, 10)}`,
      filename,
      format: "zip",
      storagePath,
      sizeBytes: stat.size,
      artifactIds: JSON.stringify([...artifactsByFilename.values()].map(a => a.id)),
    })
    .run();

  return {
    id: exportId,
    filename,
    storagePath,
    sizeBytes: stat.size,
  };
}
