import type { NewControl } from "./schema";

export function getStarterControls(workspaceId: string): NewControl[] {
  return [
    {
      id: crypto.randomUUID(),
      workspaceId,
      controlId: "VM-01",
      title: "Software Inventory",
      description: "Maintain a current inventory of all software assets and their versions using a Software Bill of Materials (SBOM).",
      category: "Vulnerability Management",
      frequency: "weekly",
      status: "not_started",
    },
    {
      id: crypto.randomUUID(),
      workspaceId,
      controlId: "VM-02",
      title: "Vulnerability Scanning",
      description: "Perform regular vulnerability scans on all software dependencies using OSV or equivalent scanner.",
      category: "Vulnerability Management",
      frequency: "weekly",
      status: "not_started",
    },
    {
      id: crypto.randomUUID(),
      workspaceId,
      controlId: "VM-03",
      title: "Known Exploited Vulnerability Monitoring",
      description: "Monitor CISA KEV catalog and flag any dependencies with known exploited vulnerabilities.",
      category: "Vulnerability Management",
      frequency: "daily",
      status: "not_started",
    },
    {
      id: crypto.randomUUID(),
      workspaceId,
      controlId: "VM-04",
      title: "Exploitation Probability Assessment",
      description: "Assess exploitation probability for identified vulnerabilities using EPSS scores.",
      category: "Vulnerability Management",
      frequency: "weekly",
      status: "not_started",
    },
    {
      id: crypto.randomUUID(),
      workspaceId,
      controlId: "VM-05",
      title: "Vulnerability Remediation Tracking",
      description: "Track remediation status for all identified vulnerabilities with defined SLAs based on severity.",
      category: "Vulnerability Management",
      frequency: "weekly",
      status: "not_started",
    },
    {
      id: crypto.randomUUID(),
      workspaceId,
      controlId: "VM-06",
      title: "Critical Vulnerability Response",
      description: "Respond to critical and KEV-listed vulnerabilities within defined timeframes.",
      category: "Vulnerability Management",
      frequency: "daily",
      status: "not_started",
    },
    {
      id: crypto.randomUUID(),
      workspaceId,
      controlId: "SCM-01",
      title: "Dependency Provenance",
      description: "Verify the provenance of all third-party dependencies and maintain records of their sources.",
      category: "Supply Chain Management",
      frequency: "monthly",
      status: "not_started",
    },
    {
      id: crypto.randomUUID(),
      workspaceId,
      controlId: "SCM-02",
      title: "CI/CD Pipeline Integrity",
      description: "Pin all CI/CD actions to exact commit SHAs to prevent supply-chain attacks.",
      category: "Supply Chain Management",
      frequency: "monthly",
      status: "not_started",
    },
    {
      id: crypto.randomUUID(),
      workspaceId,
      controlId: "AM-01",
      title: "Asset Classification",
      description: "Classify all information assets by sensitivity and apply appropriate handling procedures.",
      category: "Asset Management",
      frequency: "quarterly",
      status: "not_started",
    },
    {
      id: crypto.randomUUID(),
      workspaceId,
      controlId: "AM-02",
      title: "Change Management",
      description: "Document and approve all changes to production systems through a defined change management process.",
      category: "Asset Management",
      frequency: "weekly",
      status: "not_started",
    },
    {
      id: crypto.randomUUID(),
      workspaceId,
      controlId: "DR-01",
      title: "Evidence Retention",
      description: "Retain compliance evidence with full audit trail for a minimum of 12 months.",
      category: "Data & Records",
      frequency: "monthly",
      status: "not_started",
    },
    {
      id: crypto.randomUUID(),
      workspaceId,
      controlId: "DR-02",
      title: "Evidence Integrity",
      description: "Ensure all evidence artifacts are integrity-verified using cryptographic hashes.",
      category: "Data & Records",
      frequency: "weekly",
      status: "not_started",
    },
    {
      id: crypto.randomUUID(),
      workspaceId,
      controlId: "SAST-01",
      title: "Code Security Scanning",
      description: "Perform regular static analysis security testing on application source code.",
      category: "Application Security",
      frequency: "weekly",
      status: "not_started",
    },
    {
      id: crypto.randomUUID(),
      workspaceId,
      controlId: "SAST-02",
      title: "Secure Coding Standards",
      description: "Enforce secure coding patterns and detect anti-patterns in code.",
      category: "Application Security",
      frequency: "weekly",
      status: "not_started",
    },
    {
      id: crypto.randomUUID(),
      workspaceId,
      controlId: "SEC-01",
      title: "Secret Detection",
      description: "Scan source code and configuration for hardcoded secrets, API keys, and credentials.",
      category: "Secret Management",
      frequency: "daily",
      status: "not_started",
    },
    {
      id: crypto.randomUUID(),
      workspaceId,
      controlId: "SEC-02",
      title: "Secret Rotation",
      description: "Rotate secrets and credentials on a regular schedule.",
      category: "Secret Management",
      frequency: "quarterly",
      status: "not_started",
    },
    {
      id: crypto.randomUUID(),
      workspaceId,
      controlId: "LIC-01",
      title: "License Compliance",
      description: "Verify all third-party dependencies use approved licenses.",
      category: "License Compliance",
      frequency: "monthly",
      status: "not_started",
    },
    {
      id: crypto.randomUUID(),
      workspaceId,
      controlId: "LIC-02",
      title: "License Inventory",
      description: "Maintain a current inventory of all dependency licenses.",
      category: "License Compliance",
      frequency: "monthly",
      status: "not_started",
    },
    {
      id: crypto.randomUUID(),
      workspaceId,
      controlId: "DOCK-01",
      title: "Container Image Security",
      description: "Scan container base images for known vulnerabilities.",
      category: "Container Security",
      frequency: "weekly",
      status: "not_started",
    },
    {
      id: crypto.randomUUID(),
      workspaceId,
      controlId: "DOCK-02",
      title: "Dockerfile Best Practices",
      description: "Enforce Dockerfile security best practices (no root, pinned versions, no secrets).",
      category: "Container Security",
      frequency: "monthly",
      status: "not_started",
    },
    {
      id: crypto.randomUUID(),
      workspaceId,
      controlId: "CSPM-01",
      title: "Cloud Access Controls",
      description: "Enforce MFA and least-privilege access for all cloud accounts.",
      category: "Cloud Security",
      frequency: "weekly",
      status: "not_started",
    },
    {
      id: crypto.randomUUID(),
      workspaceId,
      controlId: "CSPM-02",
      title: "Cloud Encryption",
      description: "Ensure encryption at rest for all cloud storage and databases.",
      category: "Cloud Security",
      frequency: "monthly",
      status: "not_started",
    },
    {
      id: crypto.randomUUID(),
      workspaceId,
      controlId: "CSPM-03",
      title: "Cloud Audit Logging",
      description: "Enable and monitor cloud audit trails.",
      category: "Cloud Security",
      frequency: "weekly",
      status: "not_started",
    },
    {
      id: crypto.randomUUID(),
      workspaceId,
      controlId: "CSPM-04",
      title: "Cloud Network Security",
      description: "Restrict network access and close unnecessary ports.",
      category: "Cloud Security",
      frequency: "weekly",
      status: "not_started",
    },
    {
      id: crypto.randomUUID(),
      workspaceId,
      controlId: "DAST-01",
      title: "Transport Security",
      description: "Enforce HTTPS with valid TLS certificates and HSTS headers.",
      category: "Runtime Security",
      frequency: "weekly",
      status: "not_started",
    },
    {
      id: crypto.randomUUID(),
      workspaceId,
      controlId: "DAST-02",
      title: "Security Headers",
      description: "Configure Content-Security-Policy, X-Frame-Options, and other security headers.",
      category: "Runtime Security",
      frequency: "weekly",
      status: "not_started",
    },
    {
      id: crypto.randomUUID(),
      workspaceId,
      controlId: "DAST-03",
      title: "Endpoint Hardening",
      description: "Prevent exposure of sensitive paths and administrative endpoints.",
      category: "Runtime Security",
      frequency: "monthly",
      status: "not_started",
    },
  ];
}
